name: Build and Deploy to Azure Web App (Flask)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .
          slot-name: production
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.10.18/x64
          PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.18/x64/lib/pkgconfig
          Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.18/x64
          Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.18/x64
          Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.18/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.18/x64/lib